// scripts/test_guardian.js
// PMS 测试守护脚本 — 浏览器端到端验证
// 运行方式：node scripts/test_guardian.js

const { chromium } = require('playwright');

const BASE = 'http://localhost:5173';
const API = 'http://127.0.0.1:8001/api/v1';

// 要测试的页面（key = navigate 事件 detail 值）
const PAGES = [
  { key: 'cockpit', name: '监测驾驶舱', checks: ['随手拍', '报告数'] },
  { key: 'approval', name: '审批中心', checks: ['待我审批', '审批历史'] },
  { key: 'hazards', name: '随手拍', checks: ['随手拍', '上报'] },
  { key: 'hazardStats', name: '隐患统计', checks: ['隐患总数', '趋势'] },
  { key: 'gantt', name: '甘特图', checks: ['甘特图', '任务'] },
  { key: 'forum', name: '论坛', checks: ['论坛', '发帖'] },
  { key: 'quality', name: '质量管理', checks: ['质量', '标准'] },
  { key: 'contracts', name: '合同管理', checks: ['合同', '金额'] },
  { key: 'risks', name: '风险管理', checks: ['风险', '高风险'] },
  { key: 'resources', name: '资源调度', checks: ['资源', '设备'] },
  { key: 'export', name: '数据导出', checks: ['导出', '隐患'] },
  { key: 'notifications', name: '消息中心', checks: ['消息', '通知'] },
  { key: 'audit', name: '审计日志', checks: ['审计', '日志'] },
  { key: 'knowledgeBase', name: '知识库', checks: ['知识', '文档'] },
  { key: 'dataDictionary', name: '数据字典', checks: ['数据', '编码'] },
  { key: 'calendar', name: '日历视图', checks: ['日历', '2026'] },
  { key: 'budget', name: '预算执行', checks: ['预算', '执行'] },
  { key: 'reportWrite', name: '报告撰写', checks: ['报告', '撰写'] },
  { key: 'reportStats', name: '报告统计', checks: ['报告', '统计'] },
  { key: 'notificationSettings', name: '通知设置', checks: ['通知', '设置'] },
];

async function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

async function runTests() {
  const results = [];
  let browser;
  
  try {
    console.log('🚀 启动浏览器...');
    browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({
      viewport: { width: 1440, height: 900 }
    });
    const page = await context.newPage();

    // 收集控制台错误
    const consoleErrors = [];
    page.on('console', msg => {
      if (msg.type() === 'error') {
        consoleErrors.push(msg.text());
      }
    });

    // 1. 访问首页（触发自动登录）
    console.log('📱 访问首页...');
    await page.goto(BASE, { waitUntil: 'networkidle', timeout: 15000 });
    await sleep(3000);

    // 2. 遍历测试每个页面
    for (const { key, name, checks } of PAGES) {
      try {
        // 导航到页面
        await page.evaluate((k) => {
          window.dispatchEvent(new CustomEvent('navigate', { detail: k }));
        }, key);
        await sleep(2500);

        // 获取页面文本
        const bodyText = await page.evaluate(() => document.body.innerText);
        const pageTitle = await page.title();

        // 检查关键词
        const found = checks.filter(c => bodyText.includes(c));
        const missing = checks.filter(c => !bodyText.includes(c));

        // 检查崩溃（空白页面）
        const isBlank = bodyText.length < 50;
        const hasError = consoleErrors.length > 0;

        const result = {
          page: name,
          key,
          status: (isBlank || missing.length === checks.length) ? 'FAIL' : (missing.length > 0 ? 'PARTIAL' : 'PASS'),
          found,
          missing,
          errors: [...consoleErrors],
          length: bodyText.length,
        };

        console.log(`[${result.status}] ${name}: ${found.join(', ')}${missing.length > 0 ? ` | 缺失: ${missing.join(', ')}` : ''}`);

        results.push(result);
        consoleErrors.length = 0; // 重置错误

      } catch (e) {
        results.push({
          page: name, key,
          status: 'ERROR',
          found: [],
          missing: checks,
          errors: [e.message],
        });
        console.log(`[ERROR] ${name}: ${e.message.substring(0, 50)}`);
      }
    }

  } finally {
    if (browser) await browser.close();
  }

  // 输出报告
  const passCount = results.filter(r => r.status === 'PASS').length;
  const failCount = results.filter(r => r.status === 'FAIL').length;
  const partialCount = results.filter(r => r.status === 'PARTIAL').length;
  const errorCount = results.filter(r => r.status === 'ERROR').length;

  const report = `
# PMS 测试守护报告 - ${new Date().toLocaleString('zh-CN')}
Generated by: test_guardian.js

## 汇总
- 总计页面: ${results.length}
- ✅ PASS: ${passCount}
- ⚠️ PARTIAL: ${partialCount}
- ❌ FAIL: ${failCount}
- 💥 ERROR: ${errorCount}

## 详细结果
${results.map(r => `### ${r.page} [${r.status}]
- Key: \`${r.key}\`
- 发现: ${r.found.join(', ') || '无'}
- 缺失: ${r.missing.join(', ') || '无'}
- 控制台错误: ${r.errors.length > 0 ? r.errors.join('; ').substring(0, 100) : '无'}
- 内容长度: ${r.length}
`).join('\n')}

## 建议
${failCount > 0 ? `- **优先修复**: ${results.filter(r => r.status === 'FAIL').map(r => r.page).join(', ')}` : ''}
${partialCount > 0 ? `- **观察**: ${results.filter(r => r.status === 'PARTIAL').map(r => r.page + '(' + r.missing.join(',') + ')').join(', ')}` : ''}
${failCount === 0 && partialCount === 0 ? '- 所有页面正常 ✅' : ''}
`;

  // 保存报告
  const fs = require('fs');
  const date = new Date().toISOString().slice(0, 10);
  const reportPath = `/Users/muyi/clawd/workspace/autonomous/pms-longterm/reports/test_${date}.md`;
  fs.writeFileSync(reportPath, report, 'utf-8');

  console.log(`\n📊 报告已保存: ${reportPath}`);
  console.log(`\n汇总: ✅${passCount} ⚠️${partialCount} ❌${failCount} 💥${errorCount}`);

  return { passCount, failCount, partialCount, errorCount, results };
}

// 直接运行
runTests().catch(e => {
  console.error('测试失败:', e.message);
  process.exit(1);
});

module.exports = { runTests };
