export const users = [
  { id: 1, name: '张小明', role: '前端工程师', color: '#a855f7', avatar: 'Z' },
  { id: 2, name: '李华', role: '后端工程师', color: '#22c55e', avatar: 'L' },
  { id: 3, name: '王芳', role: 'UI设计师', color: '#ec4899', avatar: 'W' },
  { id: 4, name: '赵强', role: '测试工程师', color: '#f59e0b', avatar: 'Z' },
]

export const currentUser = users[0]

export const tasks = [
  {
    id: 1,
    title: '完成用户登录模块开发',
    description: '实现用户注册、登录、找回密码等功能，包括表单验证和错误处理。',
    status: 'done',
    priority: 'high',
    type: 'feature',
    progress: 100,
    storyPoints: 8,
    assignee: users[0],
    dueDate: '2026-03-20',
    comments: 3,
    attachments: 2,
    subtasks: [
      { id: 1, title: '设计登录表单UI', completed: true },
      { id: 2, title: '实现表单验证', completed: true },
      { id: 3, title: '对接后端API', completed: true },
    ],
  },
  {
    id: 2,
    title: '数据库性能优化',
    description: '优化慢查询，提升系统整体响应速度。',
    status: 'done',
    priority: 'medium',
    type: 'optimization',
    progress: 100,
    storyPoints: 5,
    assignee: users[1],
    dueDate: '2026-03-18',
    comments: 1,
    attachments: 1,
    subtasks: [],
  },
  {
    id: 3,
    title: '首页UI设计稿',
    description: '完成首页的整体视觉设计和交互原型。',
    status: 'review',
    priority: 'high',
    type: 'design',
    progress: 80,
    storyPoints: 13,
    assignee: users[2],
    dueDate: '2026-03-25',
    comments: 5,
    attachments: 3,
    subtasks: [
      { id: 1, title: '导航栏设计', completed: true },
      { id: 2, title: 'Banner区设计', completed: true },
      { id: 3, title: '产品展示区', completed: false },
    ],
  },
  {
    id: 4,
    title: 'API接口测试',
    description: '对所有REST API接口进行功能测试和边界测试。',
    status: 'review',
    priority: 'medium',
    type: 'testing',
    progress: 60,
    storyPoints: 5,
    assignee: users[3],
    dueDate: '2026-03-28',
    comments: 2,
    attachments: 0,
    subtasks: [],
  },
  {
    id: 5,
    title: '购物车功能开发',
    description: '实现购物车的增删改查，支持本地存储同步。',
    status: 'in-progress',
    priority: 'high',
    type: 'feature',
    progress: 45,
    storyPoints: 8,
    assignee: users[0],
    dueDate: '2026-03-30',
    comments: 4,
    attachments: 1,
    subtasks: [
      { id: 1, title: '购物车数据模型', completed: true },
      { id: 2, title: '添加商品逻辑', completed: true },
      { id: 3, title: '删除商品逻辑', completed: false },
      { id: 4, title: '结算流程', completed: false },
    ],
  },
  {
    id: 6,
    title: '用户权限系统',
    description: '设计并实现基于RBAC的权限控制系统。',
    status: 'in-progress',
    priority: 'high',
    type: 'feature',
    progress: 30,
    storyPoints: 13,
    assignee: users[1],
    dueDate: '2026-04-05',
    comments: 6,
    attachments: 2,
    subtasks: [],
  },
  {
    id: 7,
    title: '深色模式适配',
    description: '将现有UI组件适配深色主题模式。',
    status: 'in-progress',
    priority: 'low',
    type: 'feature',
    progress: 55,
    storyPoints: 5,
    assignee: users[2],
    dueDate: '2026-04-02',
    comments: 2,
    attachments: 4,
    subtasks: [],
  },
  {
    id: 8,
    title: '性能监控面板',
    description: '搭建前端性能监控面板，实时展示核心指标。',
    status: 'todo',
    priority: 'medium',
    type: 'feature',
    progress: 0,
    storyPoints: 8,
    assignee: users[0],
    dueDate: '2026-04-10',
    comments: 0,
    attachments: 0,
    subtasks: [],
  },
  {
    id: 9,
    title: '订单历史记录',
    description: '实现订单列表展示和详情查看功能。',
    status: 'todo',
    priority: 'medium',
    type: 'feature',
    progress: 0,
    storyPoints: 5,
    assignee: users[1],
    dueDate: '2026-04-12',
    comments: 0,
    attachments: 0,
    subtasks: [],
  },
  {
    id: 10,
    title: '单元测试覆盖率提升',
    description: '将现有代码的单元测试覆盖率提升至80%以上。',
    status: 'todo',
    priority: 'low',
    type: 'testing',
    progress: 0,
    storyPoints: 8,
    assignee: users[3],
    dueDate: '2026-04-15',
    comments: 1,
    attachments: 0,
    subtasks: [],
  },
  {
    id: 11,
    title: '消息通知系统',
    description: '实现站内消息和邮件通知功能。',
    status: 'todo',
    priority: 'medium',
    type: 'feature',
    progress: 0,
    storyPoints: 8,
    assignee: users[1],
    dueDate: '2026-04-18',
    comments: 0,
    attachments: 0,
    subtasks: [],
  },
  {
    id: 12,
    title: '移动端适配',
    description: '确保产品在移动设备上的良好体验。',
    status: 'todo',
    priority: 'high',
    type: 'feature',
    progress: 0,
    storyPoints: 13,
    assignee: users[2],
    dueDate: '2026-04-20',
    comments: 0,
    attachments: 0,
    subtasks: [],
  },
  {
    id: 13,
    title: '第三方支付集成',
    description: '集成支付宝和微信支付接口。',
    status: 'todo',
    priority: 'high',
    type: 'feature',
    progress: 0,
    storyPoints: 13,
    assignee: users[1],
    dueDate: '2026-04-22',
    comments: 0,
    attachments: 0,
    subtasks: [],
  },
  {
    id: 14,
    title: '用户反馈收集',
    description: '搭建用户反馈渠道，收集产品改进建议。',
    status: 'todo',
    priority: 'low',
    type: 'feature',
    progress: 0,
    storyPoints: 3,
    assignee: users[3],
    dueDate: '2026-04-25',
    comments: 0,
    attachments: 0,
    subtasks: [],
  },
]

export const activities = [
  {
    id: 1,
    user: users[0],
    action: '完成了任务',
    target: '完成用户登录模块开发',
    time: '2小时前',
  },
  {
    id: 2,
    user: users[1],
    action: '开始处理',
    target: '用户权限系统',
    time: '3小时前',
  },
  {
    id: 3,
    user: users[2],
    action: '上传了新文件',
    target: '首页设计稿v2.fig',
    time: '5小时前',
  },
  {
    id: 4,
    user: users[3],
    action: '创建了测试用例',
    target: '订单模块测试用例',
    time: '昨天',
  },
  {
    id: 5,
    user: users[0],
    action: '评论了',
    target: '购物车功能开发',
    time: '昨天',
  },
]

export const comments = [
  {
    id: 1,
    user: users[1],
    content: '这个功能的API接口已经准备好了，可以开始对接了。',
    time: '2026-03-25 14:30',
  },
  {
    id: 2,
    user: users[0],
    content: '好的，我这边尽快完成前端部分的开发。',
    time: '2026-03-25 15:20',
  },
  {
    id: 3,
    user: users[2],
    content: '设计稿已经更新，添加了深色模式的支持。',
    time: '2026-03-25 16:45',
  },
]

export const chartData = {
  area: [
    { name: '周一', value: 400 },
    { name: '周二', value: 300 },
    { name: '周三', value: 550 },
    { name: '周四', value: 450 },
    { name: '周五', value: 600 },
    { name: '周六', value: 500 },
    { name: '周日', value: 700 },
    { name: '周一', value: 450 },
    { name: '周二', value: 550 },
    { name: '周三', value: 650 },
    { name: '周四', value: 580 },
    { name: '周五', value: 720 },
    { name: '周六', value: 600 },
    { name: '周日', value: 800 },
  ],
  bar: [
    { name: '张三', tasks: 5 },
    { name: '李四', tasks: 8 },
    { name: '王五', tasks: 3 },
    { name: '赵六', tasks: 6 },
    { name: '孙七', tasks: 4 },
    { name: '周八', tasks: 7 },
    { name: '吴九', tasks: 5 },
    { name: '郑十', tasks: 9 },
    { name: '钱一', tasks: 3 },
    { name: '陈二', tasks: 6 },
  ],
  donut: [
    { name: '前端', value: 35, color: '#a855f7' },
    { name: '后端', value: 28, color: '#22c55e' },
    { name: '设计', value: 20, color: '#ec4899' },
    { name: '测试', value: 17, color: '#f59e0b' },
  ],
}

export const stats = {
  total: { value: 14, trend: 12 },
  inProgress: { value: 3, trend: -5 },
  completed: { value: 5, trend: 25 },
  members: { value: 4, trend: 0 },
}
