"""FastAPI code generator package."""

from api.services.fastapi_code_generator.models import (
    Company,
    Department,
    Role,
    User,
    Project,
    Phase,
    Milestone,
    Task,
    TaskComment,
    HazardReport,
    HazardTransfer,
    HazardRectification,
    RectificationPhoto,
    InspectionPoint,
    Inspection,
    Report,
    ApprovalNode,
    Notification,
)
from api.services.fastapi_code_generator.auth import (
    verify_password,
    hash_password,
    create_access_token,
    get_current_user,
)
from api.services.fastapi_code_generator.database import get_db, init_db

__all__ = [
    "Company",
    "Department",
    "Role",
    "User",
    "Project",
    "Phase",
    "Milestone",
    "Task",
    "TaskComment",
    "HazardReport",
    "HazardTransfer",
    "HazardRectification",
    "RectificationPhoto",
    "InspectionPoint",
    "Inspection",
    "Report",
    "ApprovalNode",
    "Notification",
    "verify_password",
    "hash_password",
    "create_access_token",
    "get_current_user",
    "get_db",
    "init_db",
]
